# Generated by Django 3.2.8 on 2021-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='img',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='authors', width_field=300),
        ),
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='books', width_field=300),
        ),
    ]
