# Generated by Django 3.2.8 on 2021-11-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0002_auto_20211106_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
    ]
