# Generated by Django 3.2.8 on 2021-11-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0003_auto_20211106_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortReview', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentApp.books')),
            ],
        ),
    ]
