# Generated by Django 3.2.8 on 2021-11-23 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0005_alter_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 17, 20, 48, 859271)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contentApp.books'),
        ),
    ]
